name: Auto Build

on:
  push:
    branches:
      - main

jobs:
  auto-build:
    name: Auto Build
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v5

      - name: Setup .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Build Test Mod
        run: |
          dotnet restore
          dotnet build -c Release

      - name: Upload Test Mod
        uses: actions/upload-artifact@v4
        with:
          name: ComputerInterface-Test
          path: bin/Release/netstandard2.1/ComputerInterface.dll